import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {TonConnectButton,useTonAddress} from '@tonconnect/ui-react';

const API=(process.env.REACT_APP_API_URL||'http://localhost:5000').replace(/\/$/,'');
const LOGO='/assets/mai-logo.jpg';
const BG='/assets/background.jpg';
const LOADING='/assets/loading.jpg';

function tg(){return window.Telegram?.WebApp||null;}
function deviceId(){let id=localStorage.getItem('mai_device_id');if(!id){id=crypto.randomUUID();localStorage.setItem('mai_device_id',id);}return id;}
async function api(path,{method='GET',body,idempotency}={}){
  const web=tg(), headers={'Content-Type':'application/json','X-MAI-Device-ID':deviceId()};
  if(web?.initData)headers['X-Telegram-Init-Data']=web.initData;
  else if(process.env.REACT_APP_DEV_USER_ID)headers['X-Dev-User']=process.env.REACT_APP_DEV_USER_ID;
  if(idempotency)headers['X-Idempotency-Key']=idempotency;
  const r=await fetch(`${API}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});
  const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d;
}
const fmt=(n,d=4)=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function hms(s){s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function short(a){return a?a.length>18?`${a.slice(0,8)}…${a.slice(-6)}`:a:'Not connected';}
function Icon({name}){const map={home:'⌂',task:'✓',friends:'♟',profile:'♙',gift:'🎁',rocket:'🚀',wallet:'◈',bolt:'ϟ',clock:'◷'};return <span className="ico">{map[name]||'✦'}</span>}
function Toast({text,onDone}){useEffect(()=>{const t=setTimeout(onDone,2600);return()=>clearTimeout(t)},[onDone]);return <div className="toast">{text}</div>}

function LoadingScreen({done}){
 const [p,setP]=useState(0);useEffect(()=>{let n=0;const t=setInterval(()=>{n=Math.min(100,n+Math.ceil(Math.random()*8));setP(n);if(n>=100){clearInterval(t);setTimeout(done,250)}},90);return()=>clearInterval(t)},[done]);
 return <div className="loading" style={{backgroundImage:`url(${LOADING})`}}><div className="loadBox"><div className="initializing">INITIALIZING...</div><div className="bar"><i style={{width:`${p}%`}}/></div><b>{p}%</b></div></div>
}
function Background(){return <div className="bg" aria-hidden="true"><div className="bgImage" style={{backgroundImage:`url(${BG})`}}/><div className="bgShade"/><div className="cloud c1"/><div className="cloud c2"/><div className="water"/><div className="stars"/><div className="beam"/></div>}

function App(){
 const [loading,setLoading]=useState(true),[boot,setBoot]=useState(null),[tab,setTab]=useState('home'),[view,setView]=useState('main'),[toast,setToast]=useState(''),[busy,setBusy]=useState(false);
 const [selectedLevel,setSelectedLevel]=useState(null);const [tasks,setTasks]=useState(null);const [referrals,setReferrals]=useState(null);const [withdrawals,setWithdrawals]=useState(null);const address=useTonAddress();
 const refresh=useCallback(async()=>{const d=await api('/api/bootstrap');setBoot(d);setTasks(d.tasks);return d;},[]);
 useEffect(()=>{const web=tg();if(web){web.ready();web.expand();web.setHeaderColor?.('#05070d');web.setBackgroundColor?.('#05070d')}refresh().catch(e=>setToast(e.message));},[refresh]);
 useEffect(()=>{if(!address||!boot?.user)return; if(address!==boot.user.walletAddress)api('/api/wallet/bind',{method:'POST',body:{address}}).then(d=>setBoot(b=>({...b,user:d.user}))).catch(e=>setToast(e.message));},[address,boot?.user?.telegramId]);
 const action=async(fn)=>{if(busy)return;setBusy(true);try{await fn()}catch(e){setToast(e.message)}finally{setBusy(false)}};
 const user=boot?.user;
 if(loading)return <LoadingScreen done={()=>setLoading(false)}/>;
 if(!boot)return <div className="fatal"><img src={LOGO}/><h2>MAI NETWORK</h2><p>Open this Mini App inside Telegram.</p>{toast&&<p>{toast}</p>}</div>;
 const go=(t)=>{setTab(t);setView('main');};
 return <div className="app"><Background/>{toast&&<Toast text={toast} onDone={()=>setToast('')}/>}<main className="screen">
   {view==='boost'?<BoostPage user={user} selectedLevel={selectedLevel} setSelectedLevel={setSelectedLevel} back={()=>setView('main')}/>:view==='promote'?<PromotePage back={()=>setView('main')} user={user} toast={setToast} refresh={refresh}/>:view==='withdraw'?<WithdrawPage back={()=>setView('main')} user={user} setBoot={setBoot} toast={setToast}/>:tab==='home'?<Home user={user} tasks={tasks} setTab={go} setView={setView} refresh={refresh} toast={setToast} busy={busy} action={action}/>:tab==='task'?<TasksPage tasks={tasks} setTasks={setTasks} user={user} setBoot={setBoot} openPromote={()=>setView('promote')} toast={setToast} action={action}/>:tab==='friends'?<FriendsPage data={referrals} setData={setReferrals} toast={setToast} setBoot={setBoot}/>:<ProfilePage user={user} openWithdraw={()=>setView('withdraw')} withdrawals={withdrawals} setWithdrawals={setWithdrawals} toast={setToast}/>} 
 </main><BottomNav tab={tab} go={go}/></div>
}

function Home({user,tasks,setTab,setView,refresh,toast,busy,action}){
 const [remain,setRemain]=useState(user.farm.remaining),[sparks,setSparks]=useState([]);
 useEffect(()=>{setRemain(user.farm.remaining)},[user.farm.remaining]);useEffect(()=>{const t=setInterval(()=>setRemain(x=>Math.max(0,x-1)),1000);return()=>clearInterval(t)},[]);
 const tap=e=>{const r=e.currentTarget.getBoundingClientRect();const batch=Array.from({length:10},(_,i)=>({id:Date.now()+i,x:e.clientX-r.left,y:e.clientY-r.top,dx:(Math.random()-.5)*130,dy:-50-Math.random()*90}));setSparks(batch);setTimeout(()=>setSparks([]),700)};
 return <div className="homePage">
  <section className="topGrid">
   <div className="brand glass"><img src={LOGO}/><div><strong>MAI NETWORK</strong><span><i className="online"/> Online</span><small>Bigger Dreams · Higher Goals</small></div></div>
   <button className="balance glass" onClick={()=>setTab('profile')}><Icon name="wallet"/><img src={LOGO}/><div><b>{fmt(user.balance,4)}</b><span>MAI</span></div><em>›</em></button>
   <div className="profileMini glass"><div className="avatar">{user.photoUrl?<img src={user.photoUrl}/>:<span>{user.firstName?.[0]||'M'}</span>}</div><div><b>{user.firstName}</b><span>LVL {user.level}</span><small>Referrals: {user.referrals.successful}</small></div></div>
   <div className="quickStack"><button className="quick glass" disabled={user.dailyBonusClaimed||busy} onClick={()=>action(async()=>{const d=await api('/api/daily-bonus',{method:'POST'});toast(`+${d.reward} MAI daily bonus`);await refresh();})}><Icon name="gift"/><span><b>Daily Bonus</b><small>{user.dailyBonusClaimed?'Claimed today':'Claim 1 MAI'}</small></span><em>›</em></button><button className="quick glass" onClick={()=>setTab('task')}><Icon name="task"/><span><b>Tasks</b><small>Complete & Earn</small></span>{tasks?.hasIncomplete&&<i className="dot"/>}<em>›</em></button></div>
  </section>
  <section className="hero"><button className="coin" onClick={tap} aria-label="MAI coin"><span className="coinGlow"/><span className="orbit o1"/><span className="orbit o2"/><img className="coinImage" src={LOGO} alt="MAI" draggable="false"/>{sparks.map(s=><i key={s.id} className="spark" style={{left:s.x,top:s.y,'--dx':`${s.dx}px`,'--dy':`${s.dy}px`}}/> )}</button><div className="rateChip"><Icon name="bolt"/> +{user.farm.rateSecond.toFixed(8)}<small> MAI / SEC</small></div></section>
  <section className="homeCards"><div className="infoCard glass"><Icon name="bolt"/><div><span>AUTO MINING</span><b>+{fmt(user.farm.rateSecond,8)} MAI / SEC</b></div></div><div className="infoCard glass"><Icon name="clock"/><div><span>FARMING TIME</span><b>{user.farm.ready?'READY':hms(remain)}</b><small>{user.farm.ready?'Claim your reward':'Server-counted mining'}</small></div></div>
   <button className="infoCard glass clickable" onClick={()=>setView('boost')}><Icon name="rocket"/><div><span>BOOST</span><b>LVL {user.level}</b><small>{user.miningSpeed} MAI / Day total</small></div><em>›</em></button>
   <button className="infoCard glass clickable" disabled={busy} onClick={()=>action(async()=>{if(!user.farm.active){await api('/api/farm/start',{method:'POST'});toast('24h farming started');}else if(user.farm.ready){const d=await api('/api/farm/claim',{method:'POST'});toast(`+${fmt(d.reward,4)} MAI claimed`);}else{toast(`Available in ${hms(remain)}`)}await refresh();})}><Icon name="gift"/><div><span>{!user.farm.active?'START FARMING':user.farm.ready?'CLAIM':'FARM REWARD'}</span><b>{user.farm.ready?`${fmt(user.farm.rateDaily,2)} MAI`:`${fmt(user.farm.pending,4)} pending`}</b><small>{user.farm.ready?'Starts next 24h automatically':hms(remain)}</small></div><em>›</em></button>
  </section><div className="tagline">✦ MAI NETWORK ✦<small>TOGETHER WE BUILD A BRIGHTER FUTURE</small></div>
 </div>
}

function BoostPage({user,selectedLevel,setSelectedLevel,back}){
 const [page,setPage]=useState(1);const per=20,pages=Math.ceil(user.maxLevel/per);const levels=useMemo(()=>Array.from({length:Math.min(per,user.maxLevel-(page-1)*per)},(_,i)=>(page-1)*per+i+1),[page,user.maxLevel]);
 if(selectedLevel){const n=selectedLevel, need=n*user.holdingStep, speed=10+(n-1)*2, missing=Math.max(0,need-user.balance), unlocked=user.balance>=need;return <PageShell title={`LEVEL ${n}`} back={()=>setSelectedLevel(null)}><div className="levelHero"><div className={unlocked?'levelSeal unlocked':'levelSeal'}>LVL<strong>{n}</strong></div></div><div className="detailRows"><Row a="Mining Speed" b={`${speed} MAI per Day`}/><Row a="Need-Holding unlock level" b={`${fmt(need,0)} MAI`}/><Row a="Your Holding" b={`${fmt(user.balance,4)} MAI`} big/><Row a="Need to unlock" b={`${fmt(missing,4)} MAI`} danger={!unlocked}/></div>{unlocked?<><div className="unlockedBtn">🔓 UNLOCKED</div><button className="secondary" onClick={()=>setSelectedLevel(null)}>CLOSE</button></>:<div className="twoBtns"><button className="goldBtn" onClick={()=>window.open('https://app.ston.fi','_blank')}>BUY</button><button className="secondary" onClick={()=>setSelectedLevel(null)}>CANCEL</button></div>}<p className="hint">Free Bonus Level adds {user.freeMiningSpeed} MAI/day to the unlocked level speed.</p></PageShell>}
 return <PageShell title="BOOST" back={back}><img className="boostLogo" src={LOGO}/><div className="boostNote"><b>HOLD MAI in your wallet boost your mining rate.</b><span>If sell MAI your level is DOWN.</span></div><div className="levelGrid">{levels.map(n=>{const speed=10+(n-1)*2,unlocked=user.balance>=n*user.holdingStep;return <button key={n} className="levelCard" onClick={()=>setSelectedLevel(n)}><b>LVL {n}</b><span>MAI LVL {n}</span><strong>Speed {speed}/Day</strong><em className={unlocked?'u':''}>{unlocked?'UNLOCK':'LOCK'}</em></button>})}</div><div className="pager"><button onClick={()=>setPage(p=>Math.max(1,p-1))}>‹</button><span>{page} / {pages}</span><button onClick={()=>setPage(p=>Math.min(pages,p+1))}>›</button></div></PageShell>
}
function Row({a,b,big,danger}) {return <div className={`row ${big?'big':''} ${danger?'danger':''}`}><span>{a}</span><b>{b}</b></div>}
function PageShell({title,back,children}){return <div className="subPage"><header><button onClick={back}>←</button><h2>{title}</h2><span/></header>{children}</div>}

function TasksPage({tasks,setTasks,user,setBoot,openPromote,toast,action}){
 const [sub,setSub]=useState('daily'),[adsBusy,setAdsBusy]=useState(false),[campaigns,setCampaigns]=useState([]),[cool,setCool]=useState(0);
 const reloadTasks=async()=>{const d=await api('/api/tasks');setTasks(d.tasks)};
 useEffect(()=>{if(sub==='exclusive')api('/api/campaigns/exclusive').then(d=>setCampaigns(d.items)).catch(e=>toast(e.message))},[sub]);
 useEffect(()=>{if(cool<=0)return;const t=setInterval(()=>setCool(x=>Math.max(0,x-1)),1000);return()=>clearInterval(t)},[cool]);
 const watch=()=>action(async()=>{setAdsBusy(true);try{const d=await api('/api/ads/start',{method:'POST'});if(!d.url)throw new Error('Ad provider did not return a URL'); const web=tg(); if(web?.openLink)web.openLink(d.url);else window.open(d.url,'_blank'); toast('Finish the ad completely, then return here.'); let tries=0;const poll=setInterval(async()=>{tries++;try{const s=await api(`/api/ads/status/${d.sessionId}`);if(s.status==='completed'&&!s.claimed_at){clearInterval(poll);const c=await api(`/api/ads/claim/${d.sessionId}`,{method:'POST'});setBoot(b=>({...b,user:c.user}));setTasks(c.tasks);setCool(tasks.ads.cooldown);toast('+1 MAI — ad verified');}else if(tries>90){clearInterval(poll);toast('Ad viewing was not completed.');}}catch{}},2000);}finally{setAdsBusy(false)}});
 return <div className="tasksPage"><div className="tabs"><button className={sub==='daily'?'active':''} onClick={()=>setSub('daily')}>Daily</button><button className={sub==='partner'?'active':''} onClick={()=>setSub('partner')}>Partner</button><button className={sub==='exclusive'?'active':''} onClick={()=>setSub('exclusive')}>Exclusive</button></div>
 {sub==='daily'&&<div className="stack"><div className="taskCard feature glass"><div><b>Watch Ads & Earn</b><span>Reward: +{tasks.ads.reward} MAI</span><small>Daily limit: {tasks.ads.remaining}/{tasks.ads.limit} · UTC reset</small></div><button disabled={adsBusy||cool>0||tasks.ads.remaining<=0} onClick={watch}>{cool>0?`${cool}s`:tasks.ads.remaining<=0?'Done':'Watch'}</button></div>{tasks.joins.map(t=><div className="taskCard glass" key={t.key}><div><b>{t.title}</b><span>+{t.reward} MAI</span><small>{t.completed?'Completed today':'Verified Telegram membership required'}</small></div><button className={t.completed?'done':''} disabled={t.completed} onClick={()=>action(async()=>{if(!t.completed){const web=tg();web?.openTelegramLink?web.openTelegramLink(t.link):window.open(t.link,'_blank');await new Promise(r=>setTimeout(r,800));const d=await api(`/api/tasks/verify/${t.key}`,{method:'POST'});setTasks(d.tasks);setBoot(b=>({...b,user:d.user}));toast(d.rewarded?`+${t.reward} MAI verified`:'Already completed');}})}>{t.completed?'✓ Done':'Join & Check'}</button></div>)}</div>}
 {sub==='partner'&&<div className="partner"><div className="sectionHead"><div><h3>Partner Promotions</h3><p>Promote a channel, group, bot, website or link.</p></div><button className="goldBtn compact" onClick={openPromote}>＋ Add to Promote</button></div><div className="promoInfo glass"><Icon name="rocket"/><div><b>Reach the MAI community</b><p>Choose a promotion limit and pay with MAI or GRAM. Every campaign stays pending until admin approval.</p><div className="chips"><span>✓ Approval control</span><span>✓ Limit tracking</span><span>✓ MAI / GRAM</span></div></div></div></div>}
 {sub==='exclusive'&&<div className="stack"><div className="sectionHead"><div><h3>Exclusive</h3><p>Approved partner missions and official MAI gifts.</p></div></div>{campaigns.length?campaigns.map(c=><div className="taskCard glass" key={c.id}><div><b>{c.title}</b><span>{c.type} · {c.reward_per_user>0?`+${c.reward_per_user} MAI`:'Partner mission'}</span><small>{c.completed_count}/{c.target_count} completed</small></div><button onClick={()=>action(async()=>{window.open(c.target_url,'_blank');if(c.verification_type==='telegram_member'||c.verification_type==='manual'){await new Promise(r=>setTimeout(r,900));const d=await api(`/api/campaigns/${c.id}/complete`,{method:'POST'});setBoot(b=>({...b,user:d.user}));toast(d.reward?`+${d.reward} MAI`:'Mission completed');}})}>Open</button></div>):<div className="empty glass">No exclusive campaigns yet.</div>}</div>}
 </div>
}

function PromotePage({back,user,toast,refresh}){
 const [type,setType]=useState('Channel'),[title,setTitle]=useState(''),[url,setUrl]=useState(''),[desc,setDesc]=useState(''),[count,setCount]=useState(100),[pay,setPay]=useState('MAI'),[quote,setQuote]=useState({MAI:10,GRAM:.1}),[busy,setBusy]=useState(false);
 useEffect(()=>{const t=setTimeout(()=>api('/api/campaigns/quote',{method:'POST',body:{targetCount:count}}).then(d=>setQuote(d)).catch(()=>{}),250);return()=>clearTimeout(t)},[count]);
 const submit=async()=>{setBusy(true);try{const d=await api('/api/campaigns',{method:'POST',body:{type,title,targetUrl:url,description:desc,targetCount:Number(count),paymentMethod:pay}});toast(`Campaign #${d.campaign.id} submitted for approval`);await refresh();back();}catch(e){toast(e.message)}finally{setBusy(false)}};
 return <PageShell title="ADD TO PROMOTE" back={back}><div className="form glass"><label>Promotion Type<select value={type} onChange={e=>setType(e.target.value)}>{['Channel','Group','Bot','Website','Link'].map(x=><option key={x}>{x}</option>)}</select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Your campaign name"/></label><label>Link<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></label><label>Description<textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Short description"/></label><label>Promote Limit<input type="number" min="1" value={count} onChange={e=>setCount(e.target.value)}/></label><div className="payTabs"><button className={pay==='MAI'?'active':''} onClick={()=>setPay('MAI')}>Pay MAI</button><button className={pay==='GRAM'?'active':''} onClick={()=>setPay('GRAM')}>Pay GRAM</button></div><div className="quote"><span>Promotion cost</span><b>{fmt(quote[pay],pay==='GRAM'?3:2)} {pay}</b></div><small className="hint">MAI payment is deducted immediately. GRAM campaigns stay payment-pending until your payment is verified and admin approves the campaign.</small><button className="goldBtn full" disabled={busy||!title||!url} onClick={submit}>{busy?'Submitting…':'Submit Promotion'}</button></div></PageShell>
}

function FriendsPage({data,setData,toast,setBoot}){
 const load=useCallback(()=>api('/api/referrals').then(d=>setData(d)).catch(e=>toast(e.message)),[setData,toast]);useEffect(()=>{load()},[load]);
 if(!data)return <div className="empty glass">Loading referrals…</div>;
 const share=()=>{const text='Join MAI Network and start mining with me 🚀';const u=`https://t.me/share/url?url=${encodeURIComponent(data.link)}&text=${encodeURIComponent(text)}`;tg()?.openTelegramLink?tg().openTelegramLink(u):window.open(u,'_blank')};
 return <div className="friendsPage"><div className="refHero glass"><img src={LOGO}/><h2>Invite Friends</h2><p>Build your network. Rewards unlock only after your friend becomes an active MAI user.</p><div className="refStats"><div><b>{data.successful}</b><span>Successful</span></div><div><b>{data.pending}</b><span>Pending</span></div><div><b>{fmt(data.totalEarned,0)}</b><span>MAI Earned</span></div></div><button className="goldBtn full" onClick={share}>Invite Friend</button><button className="copyBtn" onClick={()=>navigator.clipboard.writeText(data.link).then(()=>toast('Referral link copied'))}>Copy Link</button></div><h3>Milestone Rewards</h3><div className="milestones">{data.milestones.map(m=><div className={`mile glass ${m.unlocked?'ready':''}`} key={m.count}><div><b>{m.count} Friends</b><span>+{m.reward} MAI</span></div><button disabled={!m.unlocked||m.claimed} onClick={()=>api(`/api/referrals/milestones/${m.count}`,{method:'POST'}).then(d=>{setBoot(b=>({...b,user:d.user}));toast(`+${d.reward} MAI milestone`);load()}).catch(e=>toast(e.message))}>{m.claimed?'Claimed':m.unlocked?'Claim':'Locked'}</button></div>)}</div><h3>Referral History</h3><div className="stack">{data.items.length?data.items.map(x=><div className="refRow glass" key={x.telegram_id}><div className="avatar small">{x.photo_url?<img src={x.photo_url}/>:<span>{x.first_name?.[0]}</span>}</div><div><b>{x.first_name}</b><span>{new Date(x.created_at).toLocaleDateString()}</span></div><em className={x.referral_qualified?'ok':'pending'}>{x.referral_qualified?'Successful':'Pending'}</em></div>):<div className="empty glass">No referrals yet.</div>}</div></div>
}

function ProfilePage({user,openWithdraw,withdrawals,setWithdrawals,toast}){
 useEffect(()=>{api('/api/withdrawals').then(d=>setWithdrawals(d)).catch(()=>{})},[]);
 const next=Math.min(user.maxLevel,user.level+1), need=next*user.holdingStep, remain=Math.max(0,need-user.balance), pct=user.level>=user.maxLevel?100:Math.min(100,(user.balance-(user.level*user.holdingStep))/user.holdingStep*100);
 return <div className="profilePage"><div className="profileHero glass"><div className="avatar big">{user.photoUrl?<img src={user.photoUrl}/>:<span>{user.firstName?.[0]}</span>}</div><h2>{user.firstName}</h2><span>@{user.username||'telegram-user'}</span><div className="badges"><i>LVL {user.level}</i><i>{user.referrals.successful} Referrals</i><i>Verified Telegram</i></div></div><div className="walletCard glass"><div className="sectionHead"><div><h3>Wallet Center</h3><p>{short(user.walletAddress)}</p></div><TonConnectButton/></div><div className="securityLine"><span>TON Connect</span><b className={user.walletAddress?'green':''}>{user.walletAddress?'Connected':'Not connected'}</b></div></div><div className="holding glass"><div className="sectionHead"><div><h3>MAI Holding</h3><p>Holding determines your mining level.</p></div><b>{fmt(user.balance,2)} MAI</b></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="next"><span>Current LVL {user.level}</span><span>{user.level<user.maxLevel?`${fmt(remain,0)} MAI to LVL ${next}`:'MAX LEVEL'}</span></div></div><button className="withdrawHero glass" onClick={openWithdraw}><Icon name="wallet"/><div><b>Withdraw MAI</b><span>Secure withdrawal center</span></div><em>›</em></button><div className="security glass"><h3>Security Center</h3><div className="securityLine"><span>Telegram Authentication</span><b className="green">Verified</b></div><div className="securityLine"><span>Wallet Binding</span><b className={user.walletAddress?'green':''}>{user.walletAddress?'Active':'Required'}</b></div><div className="securityLine"><span>Locked Balance</span><b>{fmt(user.lockedBalance,2)} MAI</b></div><p className="hint">Withdrawals use server-side balance checks, idempotency, rate limits, wallet-change lock, risk scoring and admin review thresholds.</p></div><div className="settings glass"><h3>Settings & Help</h3><button>🔔 Notifications <em>›</em></button><button>🌐 Language <em>›</em></button><button>🛡 Terms & Privacy <em>›</em></button><button>💬 Support <em>›</em></button></div></div>
}

function WithdrawPage({back,user,setBoot,toast}){
 const [amount,setAmount]=useState(''),[history,setHistory]=useState([]),[min,setMin]=useState(500),[busy,setBusy]=useState(false);
 const load=useCallback(()=>api('/api/withdrawals').then(d=>{setHistory(d.items);setMin(d.minWithdrawal)}).catch(e=>toast(e.message)),[toast]);useEffect(()=>{load()},[load]);
 const submit=async()=>{const a=Number(amount);if(!confirm(`Withdraw ${a} MAI to ${short(user.walletAddress)}?`))return;setBusy(true);try{const d=await api('/api/withdrawals',{method:'POST',body:{amount:a},idempotency:crypto.randomUUID()});setBoot(b=>({...b,user:d.user}));toast(`Withdrawal submitted: ${d.withdrawal.status}`);setAmount('');load()}catch(e){toast(e.message)}finally{setBusy(false)}};
 return <PageShell title="WITHDRAW" back={back}><div className="withdrawBox glass"><div className="balanceBig"><span>Available Balance</span><b>{fmt(user.balance,4)} MAI</b></div><div className="miniGrid"><div><span>Minimum</span><b>{fmt(min,0)} MAI</b></div><div><span>Locked</span><b>{fmt(user.lockedBalance,2)} MAI</b></div></div><label>Amount<div className="amount"><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={`Min ${min}`}/><button onClick={()=>setAmount(String(user.balance))}>MAX</button></div></label><div className="walletDest"><span>Destination</span><b>{short(user.walletAddress)}</b></div><button className="goldBtn full holdBtn" disabled={busy||!user.walletAddress||Number(amount)<min||Number(amount)>user.balance} onClick={submit}>{busy?'Checking…':'HOLD TO WITHDRAW'}</button><p className="hint">New wallet bindings may have a security lock. Suspicious multi-account/device patterns can be sent to manual review according to server policy.</p></div><h3>Withdrawal History</h3><div className="stack">{history.length?history.map(w=><div className="history glass" key={w.id}><div><b>{fmt(w.amount,2)} MAI</b><span>{new Date(w.created_at).toLocaleString()}</span><small>{short(w.wallet_address)}</small></div><em className={`st ${w.status}`}>{w.status}</em></div>):<div className="empty glass">No withdrawals yet.</div>}</div></PageShell>
}

function BottomNav({tab,go}){return <nav className="bottomNav">{[['home','Home'],['task','Tasks'],['friends','Friends'],['profile','Profile']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>go(id)}><Icon name={id}/><span>{label}</span></button>)}</nav>}
export default App;
